export default {
    "ABW": {"name": "Aruba"},
    "AFG": {"name": "Afghanistan"},
    "AGO": {"name": "Angola"},
    "AIA": {"name": "Anguilla"},
    "ALA": {"name": "Åland Islands"}, 
    "ALB": {"name": "Albania"},
    "AND": {"name": "Andorra"},
    "ANT": {"name": "Netherlands Antilles"}, 
    "ARE": {"name": "United Arab Emirates"}, 
    "ARG": {"name": "Argentina"},
    "ARM": {"name": "Armenia"},
    "ASM": {"name": "American Samoa"}, 
    "ATA": {"name": "Antarctica"},
    "ATF": {"name": "French Southern Territories"}, 
    "ATG": {"name": "Antigua and Barbuda"},  
    "AUS": {"name": "Australia"},
    "AUT": {"name": "Austria"},
    "AZE": {"name": "Azerbaijan"},
    "BDI": {"name": "Burundi"},
    "BEL": {"name": "Belgium"},
    "BEN": {"name": "Benin"},
    "BFA": {"name": "Burkina Faso"}, 
    "BGD": {"name": "Bangladesh"},
    "BGR": {"name": "Bulgaria"},
    "BHR": {"name": "Bahrain"},
    "BHS": {"name": "Bahamas"},
    "BIH": {"name": "Bosnia and Herzegovina"}, 
    "BLM": {"name": "Saint Barthélemy"}, 
    "BLR": {"name": "Belarus"},
    "BLZ": {"name": "Belize"},
    "BMU": {"name": "Bermuda"},
    "BOL": {"name": "Bolivia"},
    "BRA": {"name": "Brazil"},
    "BRB": {"name": "Barbados"},
    "BRN": {"name": "Brunei Darussalam"}, 
    "BTN": {"name": "Bhutan"},
    "BVT": {"name": "Bouvet Island"}, 
    "BWA": {"name": "Botswana"},
    "CAF": {"name": "Central African Republic"}, 
    "CAN": {"name": "Canada"},
    "CCK": {"name": "Cocos"}, 
    "CHE": {"name": "Switzerland"},
    "CHL": {"name": "Chile"},
    "CHN": {"name": "China"},
    "CIV": {"name": "Côte d'Ivoire"}, 
    "CMR": {"name": "Cameroon"},
    "COD": {"name": "the Democratic Republic of the Congo"},
    "COG": {"name": "Congo"},
    "COK": {"name": "Cook Islands"}, 
    "COL": {"name": "Colombia"},
    "COM": {"name": "Comoros"},
    "CPV": {"name": "Cape Verde"}, 
    "CRI": {"name": "Costa Rica"}, 
    "CUB": {"name": "Cuba"},
    "CXR": {"name": "Christmas Island"}, 
    "CYM": {"name": "Cayman Islands"}, 
    "CYP": {"name": "Cyprus"},
    "CZE": {"name": "Czech Republic"}, 
    "DEU": {"name": "Germany"},
    "DJI": {"name": "Djibouti"},
    "DMA": {"name": "Dominica"},
    "DNK": {"name": "Denmark"},
    "DOM": {"name": "Dominican Republic"}, 
    "DZA": {"name": "Algeria"},
    "ECU": {"name": "Ecuador"},
    "EGY": {"name": "Egypt"},
    "ERI": {"name": "Eritrea"},
    "ESH": {"name": "Western Sahara"}, 
    "ESP": {"name": "Spain"},
    "EST": {"name": "Estonia"},
    "ETH": {"name": "Ethiopia"},
    "FIN": {"name": "Finland"},
    "FJI": {"name": "Fiji"},
    "FLK": {"name": "Falkland Islands"},
    "FRA": {"name": "France"},
    "FRO": {"name": "Faroe Islands"}, 
    "FSM": {"name": "Micronesia,"},
    "GAB": {"name": "Gabon"},
    "GBR": {"name": "United Kingdom"}, 
    "GEO": {"name": "Georgia"},
    "GGY": {"name": "Guernsey"},
    "GHA": {"name": "Ghana"},
    "GIB": {"name": "Gibraltar"},
    "GIN": {"name": "Guinea"},
    "GLP": {"name": "Guadeloupe"},
    "GMB": {"name": "Gambia"},
    "GNB": {"name": "Guinea-Bissau"}, 
    "GNQ": {"name": "Equatorial Guinea"}, 
    "GRC": {"name": "Greece"},
    "GRD": {"name": "Grenada"},
    "GRL": {"name": "Greenland"},
    "GTM": {"name": "Guatemala"},
    "GUF": {"name": "French Guiana"}, 
    "GUM": {"name": "Guam"},
    "GUY": {"name": "Guyana"},
    "HKG": {"name": "Hong Kong"}, 
    "HMD": {"name": "Heard Island"},
    "HND": {"name": "Honduras"},
    "HRV": {"name": "Croatia"},
    "HTI": {"name": "Haiti"},
    "HUN": {"name": "Hungary"},
    "IDN": {"name": "Indonesia"},
    "IMN": {"name": "Isle of Man"}, 
    "IND": {"name": "India"},
    "IOT": {"name": "British Indian"},
    "IRL": {"name": "Ireland"},
    "IRN": {"name": "Iran,"}, 
    "IRQ": {"name": "Iraq"},
    "ISL": {"name": "Iceland"},
    "ISR": {"name": "Israel"},
    "ITA": {"name": "Italy"},
    "JAM": {"name": "Jamaica"},
    "JEY": {"name": "Jersey"},
    "JOR": {"name": "Jordan"},
    "JPN": {"name": "Japan"},
    "KAZ": {"name": "Kazakhstan"},
    "KEN": {"name": "Kenya"},
    "KGZ": {"name": "Kyrgyzstan"},
    "KHM": {"name": "Cambodia"},
    "KIR": {"name": "Kiribati"},
    "KNA": {"name": "Saint Kitts and Nevis"},
    "KOR": {"name": "South Korea,"}, 
    "KWT": {"name": "Kuwait"},
    "LAO": {"name": "Lao People's Democratic Republic "},
    "LBN": {"name": "Lebanon"},
    "LBR": {"name": "Liberia"},
    "LBY": {"name": "Libyan Arab Jamahiriya"}, 
    "LCA": {"name": "Saint Lucia"}, 
    "LIE": {"name": "Liechtenstein"},
    "LKA": {"name": "Sri Lanka"}, 
    "LSO": {"name": "Lesotho"},
    "LTU": {"name": "Lithuania"},
    "LUX": {"name": "Luxembourg"},
    "LVA": {"name": "Latvia"},
    "MAC": {"name": "Macao"},
    "MAF": {"name": "Saint Martin"}, 
    "MAR": {"name": "Morocco"},
    "MCO": {"name": "Monaco"},
    "MDA": {"name": "Moldova,"},
    "MDG": {"name": "Madagascar"},
    "MDV": {"name": "Maldives"},
    "MEX": {"name": "Mexico"},
    "MHL": {"name": "Marshall Islands"}, 
    "MKD": {"name": "Macedonia,"},
    "MLI": {"name": "Mali"},
    "MLT": {"name": "Malta"},
    "MMR": {"name": "Myanmar"},
    "MNE": {"name": "Montenegro"},
    "MNG": {"name": "Mongolia"},
    "MNP": {"name": "Northern Mariana Islands"}, 
    "MOZ": {"name": "Mozambique"},
    "MRT": {"name": "Mauritania"},
    "MSR": {"name": "Montserrat"},
    "MTQ": {"name": "Martinique"},
    "MUS": {"name": "Mauritius"},
    "MWI": {"name": "Malawi"},
    "MYS": {"name": "Malaysia"},
    "MYT": {"name": "Mayotte"},
    "NAM": {"name": "Namibia"},
    "NCL": {"name": "New Caledonia"}, 
    "NER": {"name": "Niger"},
    "NFK": {"name": "Norfolk Island"}, 
    "NGA": {"name": "Nigeria"},
    "NIC": {"name": "Nicaragua"},
    "NIU": {"name": "Niue"},
    "NLD": {"name": "Netherlands"},
    "NOR": {"name": "Norway"},
    "NPL": {"name": "Nepal"},
    "NRU": {"name": "Nauru"},
    "NZL": {"name": "New Zealand"}, 
    "OMN": {"name": "Oman"},
    "PAK": {"name": "Pakistan"},
    "PAN": {"name": "Panama"},
    "PCN": {"name": "Pitcairn"},
    "PER": {"name": "Peru"},
    "PHL": {"name": "Philippines"},
    "PLW": {"name": "Palau"},
    "PNG": {"name": "Papua New Guinea"}, 
    "POL": {"name": "Poland"},
    "PRI": {"name": "Puerto Rico"}, 
    "PRK": {"name": "North Korea,"},
    "PRT": {"name": "Portugal"},
    "PRY": {"name": "Paraguay"},
    "PSE": {"name": "Palestinian"}, 
    "PYF": {"name": "French Polynesia"}, 
    "QAT": {"name": "Qatar"},
    "REU": {"name": "Réunion"},
    "ROU": {"name": "Romania"},
    "RUS": {"name": "Russian Federation"}, 
    "RWA": {"name": "Rwanda"},
    "SAU": {"name": "Saudi Arabia"}, 
    "SDN": {"name": "Sudan"},
    "SEN": {"name": "Senegal"},
    "SGP": {"name": "Singapore"},
    "SGS": {"name": "South Georgia"},
    "SHN": {"name": "Saint Helena"},
    "SJM": {"name": "Svalbard and Jan Mayen"},
    "SLB": {"name": "Solomon Islands"}, 
    "SLE": {"name": "Sierra Leone"}, 
    "SLV": {"name": "El Salvador"}, 
    "SMR": {"name": "San Marino"}, 
    "SOM": {"name": "Somalia"},
    "SPM": {"name": "Saint Pierre and Miquelon"},
    "SRB": {"name": "Serbia"},
    "STP": {"name": "Sao Tome and Principe"}, 
    "SUR": {"name": "Suriname"},
    "SVK": {"name": "Slovakia"},
    "SVN": {"name": "Slovenia"},
    "SWE": {"name": "Sweden"},
    "SWZ": {"name": "Swaziland"},
    "SYC": {"name": "Seychelles"},
    "SYR": {"name": "Syrian Arab Republic"}, 
    "TCA": {"name": "Turks and Caicos Islands"}, 
    "TCD": {"name": "Chad"},
    "TGO": {"name": "Togo"},
    "THA": {"name": "Thailand"},
    "TJK": {"name": "Tajikistan"},
    "TKL": {"name": "Tokelau"},
    "TKM": {"name": "Turkmenistan"},
    "TLS": {"name": "Timor-Leste"}, 
    "TON": {"name": "Tonga"},
    "TTO": {"name": "Trinidad and Tobago"}, 
    "TUN": {"name": "Tunisia"},
    "TUR": {"name": "Turkey"},
    "TUV": {"name": "Tuvalu"},
    "TWN": {"name": "Taiwan,"}, 
    "TZA": {"name": "Tanzania,"}, 
    "UGA": {"name": "Uganda"},
    "UKR": {"name": "Ukraine"},
    "UMI": {"name": "United States"},
    "URY": {"name": "Uruguay"},
    "USA": {"name": "United States"}, 
    "UZB": {"name": "Uzbekistan"},
    "VAT": {"name": "Holy See"}, 
    "VCT": {"name": "Saint Vincent"}, 
    "VEN": {"name": "Venezuela,"},
    "VGB": {"name": "Virgin Islands, British"},
    "VIR": {"name": "Virgin Islands U.S."}, 
    "VNM": {"name": "Viet Nam"}, 
    "VUT": {"name": "Vanuatu"},
    "WLF": {"name": "Wallis and Futuna"}, 
    "WSM": {"name": "Samoa"},
    "YEM": {"name": "Yemen"},
    "ZAF": {"name": "South Africa"}, 
    "ZMB": {"name": "Zambia"},
    "ZWE": {"name": "Zimbabwe"},
}
