export default { 
  "Angola": { "abbr": "afago"},
  "Burundi": { "abbr": "afbdi"},
  "Benin": { "abbr": "afben"},
  "Burkina Faso": { "abbr": "afbfa"},
  "Central African Republic": { "abbr": "afcaf"},
  "Côte d'Ivoire ": { "abbr": "afciv"},
  "Cameron": { "abbr": "afcmr"},
  "Congo, the Democratic Republic of the": { "abbr": "afcod"},
  "Congo": { "abbr": "afcog"},
  "Comoros": { "abbr": "afcom"},
  "Cape Verde": { "abbr": "afcpv"},
  "Djibouti": { "abbr": "afdji"},
  "Algeria": { "abbr": "afdza"},
  "Egypt": { "abbr": "afegy"},
  "Eritrea": { "abbr": "aferi"},
  "Western Sahara ": { "abbr": "afesh"},
  "Ethiopia": { "abbr": "afeth"},
  "Gabon": { "abbr": "afgab"},
  "Ghana": { "abbr": "afgha"},
  "Guinea": { "abbr": "afgin"},
  "Gambia": { "abbr": "afgmb"},
  "Guinea-Bissau": { "abbr": "afgnb"},
  "Equatorial Guinea": { "abbr": "afgnq"},
  "Kenya": { "abbr": "afken"},
  "Liberia": { "abbr": "aflbr"},
  "Morocco": { "abbr": "afmar"},
  "Madagascar": { "abbr": "afmdg"},
  "Mali": { "abbr": "afmli"},
  "Mozambique": { "abbr": "afmoz"},
  "Mauritania": { "abbr": "afmrt"},
  "Mauritius": { "abbr": "afmus"},
  "Mozambique": { "abbr": "afmoz"},
  "Mozambique": { "abbr": "afmoz"},
  "Mozambique": { "abbr": "afmoz"},
  "Mozambique": { "abbr": "afmoz"},
  "Mozambique": { "abbr": "afmoz"},
  "Mozambique": { "abbr": "afmoz"},
  "Mozambique": { "abbr": "afmoz"},
};

